Repository intellisysdcorp/covid-safe-paths, pull requests merged in 2020-07, with the labels that each got.

#114 Update notification
  app/locales/en.json
  app/locales/es.json
  app/services/VersionCheckService.js
  package.json
  yarn.lock
Labels: ready for review

#109 Add some dialogs in sponsors for feedbacks and advices
  app/assets/images/sponsors/12.png
  app/locales/ar.json
  app/locales/da.json
  app/locales/en.json
  app/locales/es.json
  app/locales/fil.json
  app/locales/fr.json
  app/locales/ht.json
  app/locales/id.json
  app/locales/it.json
  app/locales/ja.json
  app/locales/ml.json
  app/locales/nl.json
  app/locales/pl.json
  app/locales/pt_BR.json
  app/locales/ro.json
  app/locales/ru.json
  app/locales/sk.json
  app/locales/vi.json
  app/locales/zh_Hant.json
  app/views/DR/News/Details.js
  app/views/DR/Sponsors/List.js
  app/views/DR/Sponsors/index.js
  app/views/DialogAdvices.js
Labels: approved

#115 Fix CEGES logo sponsor
  app/assets/images/sponsors/12.png
Labels: Ready for merge, approved

#116 Changing icon of notification on Android
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: ready for review

#117 Solving form feedbacks
  app/components/DR/Input/index.js
  app/components/DR/PhoneInput/index.js
  app/locales/es.json
  app/views/DR/EpidemiologicalResponseScreen/epidemiologicalStatus.js
  app/views/DR/EpidemiologicalResponseScreen/index.js
  app/views/DR/EpidemiologicalResponseScreen/useFor.js
  app/views/DR/ReportScreen/ReportType.js
  app/views/DR/UserInfoScreen/index.js
  app/views/DR/UserInfoScreen/positiveOnboarding.js
  ios/Podfile.lock
Labels: ready for review

#119 Fix: Modify the way the FAQ is displayed
  app/views/DR/FAQ/index.js
Labels: approved

#120 Fix report go back
  app/views/DR/ReportScreen/index.js
Labels: ready for review

#121 Fixing performance leaks
  app/views/DR/ReportScreen/ReportType.js
  app/views/DR/UserInfoScreen/index.js
Labels: approved

#118 Fix sponsors dialogs
  app/locales/ar.json
  app/locales/da.json
  app/locales/en.json
  app/locales/es.json
  app/locales/fil.json
  app/locales/fr.json
  app/locales/ht.json
  app/locales/id.json
  app/locales/it.json
  app/locales/ja.json
  app/locales/ml.json
  app/locales/nl.json
  app/locales/pl.json
  app/locales/pt_BR.json
  app/locales/ro.json
  app/locales/ru.json
  app/locales/sk.json
  app/locales/vi.json
  app/locales/zh_Hant.json
  app/views/DR/News/Details.js
  app/views/DR/Sponsors/index.js
Labels: approved

#122 Fix the location share dialog.
  app/helpers/General.js
  app/views/DR/ReportScreen/ReportType.js
  app/views/DR/UserInfoScreen/index.js
  app/views/DR/UserInfoScreen/positiveOnboarding.js
Labels: ready for review

#123 New logo of CEGES
  app/assets/images/sponsors/12.png
Labels: approved

#124 Fix continue button in terms of use
  app/components/EulaModal.js
  app/constants/DR/buttonStyles.js
  app/views/__tests__/__snapshots__/Import.spec.js.snap
Labels: approved

#126 Fix baseUrl
  app/constants/DR/baseUrls.js
Labels: approved

#127 Fixing background on about screen
  app/views/About.js
Labels: approved

#129 improve import Locations UI
  app/locales/en.json
  app/locales/es.json
  app/views/Import.js
  app/views/__tests__/__snapshots__/Import.spec.js.snap
Labels: approved

#128 Fixing navigation on LocationTracking Screen, go back don't work propperly
  app/views/LocationTracking.js
  app/views/__tests__/__snapshots__/LocationTracking.spec.js.snap
Labels: Ready for merge

#130 Icon replaced with one with more borders
  android/app/src/main/res/mipmap-hdpi/isotipo_covi.png
  android/app/src/main/res/mipmap-mdpi/isotipo_covi.png
  android/app/src/main/res/mipmap-xhdpi/isotipo_covi.png
  android/app/src/main/res/mipmap-xxhdpi/isotipo_covi.png
  android/app/src/main/res/mipmap-xxxhdpi/isotipo_covi.png
Labels: approved

#132 fixing margin in legal advice screen
  app/views/Licenses.js
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
Labels: Has comments

#133 fix label font-size and update snapshots
  app/components/Button.js
  app/components/__tests__/__snapshots__/Button.spec.js.snap
  app/views/LocationTracking.js
Labels: ready for review

#134 legal advice feedback fix & margin top in onboarding fix
  app/components/EulaModal.js
  app/views/Licenses.js
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
Labels: approved

#131 Added spiner actovity indicator
  app/components/DR/ActionCards/List.js
  app/components/DR/ActivityIndicator.js
  app/views/DR/Aurora/index.js
  app/views/DR/News/Details.js
  app/views/DR/News/News.js
  app/views/DR/Sponsors/index.js
Labels: Ready for merge, approved

#135 Changed dialog wording for negatives
  app/locales/en.json
  app/locales/es.json
Labels: approved

#136 Feat: changing statistics data endpoint
  .env
  .env.release
  app/views/DR/HomeScreen/index.js
Labels: approved

#138 Sending IamPositive to /Form endpoint
  app/views/DR/UserInfoScreen/index.js
Labels: approved

#137 Fixing language bug in Terms and conditions and Date roll in Exposure History
  app/Entry.js
  app/components/EulaModal.js
  app/views/ExposureHistory/MonthGrid.js
  app/views/onboarding/Onboarding1.js
Labels: approved

#139 Changed the webView in Sponsors
  app/components/DR/ActivityIndicator.js
  app/views/DR/News/Details.js
  app/views/DR/Sponsors/index.js
Labels: approved

#141 Change icons in Bulletins and Advices
  app/components/DR/List.js
  app/views/DR/News/Advices.js
  app/views/DR/News/Bulletins.js
Labels: approved

#140 Adding dynamic tokens and deleting GOV_DO_TOKEN
  app/constants/DR/baseUrls.js
  app/helpers/DR/validateResponse.js
  app/helpers/Intersect.js
  app/services/DR/getToken.js
  app/services/LocationService.js
  app/views/DR/ReportScreen/ReportScreenQuestions.js
  app/views/DR/UserInfoScreen/index.js
Labels: approved

#142 Adding notification for new bulletin
  app/NavEntry.js
  app/locales/en.json
  app/locales/es.json
Labels: approved

#146 Solving icon notification problem in Android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-hdpi/ic_notification.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_notification.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_notification.png
Labels: ready for review

#143 Release 1.2.4
  android/app/build.gradle
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: approved

#145 Add label in date of dashboard
  app/locales/ar.json
  app/locales/da.json
  app/locales/en.json
  app/locales/es.json
  app/locales/fil.json
  app/locales/fr.json
  app/locales/ht.json
  app/locales/id.json
  app/locales/it.json
  app/locales/ja.json
  app/locales/ml.json
  app/locales/nl.json
  app/locales/pl.json
  app/locales/pt_BR.json
  app/locales/ro.json
  app/locales/ru.json
  app/locales/sk.json
  app/locales/vi.json
  app/locales/zh_Hant.json
  app/views/DR/HomeScreen/index.js
Labels: approved

#147 Changing how Terms&Condition take the appLocale
  app/views/DR/Terms&Condition/index.js
Labels: approved
