Repository intellisysdcorp/covid-safe-paths, pull requests merged in 2020-06, with the labels that each got.

#59 Epidemiological response screen
  app/Entry.js
  app/assets/images/covidFree.jpg
  app/assets/images/waitingResults.jpg
  app/components/DR/Header/style.js
  app/components/DR/ToggleButtons.js
  app/constants/colors.js
  app/locales/en.json
  app/locales/es.json
  app/views/DR/EpidemiologicalResponseScreen/epidemiologicalStatus.js
  app/views/DR/EpidemiologicalResponseScreen/index.js
  app/views/DR/EpidemiologicalResponseScreen/mentalHealthAdvices.js
  app/views/DR/ReportScreen/ReportScreenQuestions.js
  app/views/DR/UserInfoScreen/index.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  app/views/onboarding/Onboarding2.js
  app/views/onboarding/Onboarding3.js
  app/views/onboarding/Onboarding4.js
Labels: ready for review

#60 Epidemiological random tips
  app/views/DR/EpidemiologicalResponseScreen/epidemiologicalStatus.js
  app/views/DR/EpidemiologicalResponseScreen/mentalHealthAdvices.js
Labels: ready for review

#71 Develop update from production
  android/app/src/main/res/drawable/splash.png
  app/constants/DR/baseUrls.js
  app/helpers/Fetch.js
  app/helpers/Request.js
  app/helpers/__tests__/fetch.spec.js
  app/services/DR/getAllCases.js
  app/views/DR/News/Bulletins.js
  app/views/DR/News/News.js
  app/views/DR/ReportScreen/ReportScreenQuestions.js
  app/views/DR/ReportScreen/sections/StepCovidContact.js
  app/views/DR/UserInfoScreen/index.js
  app/views/LocationTracking.js
  app/views/__tests__/__snapshots__/LocationTracking.spec.js.snap
Labels: ready for review

#58 Health authorities
  .env.release
  app/Entry.js
  app/constants/DR/healthcare-authorities.yaml
  app/helpers/Intersect.js
  app/locales/en.json
  app/locales/es.json
  app/services/BackgroundTaskService.js
  app/services/HCAService.js
  app/services/LocationService.js
  app/services/__tests__/HCAService.spec.js
  app/views/ChooseProvider.js
  app/views/DR/UserInfoScreen/index.js
  app/views/LocationTracking.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  app/views/onboarding/Onboarding5.js
  ios/Podfile.lock
Labels: Ready for merge, ready for review

#82 Provinces picker-Android
  app/views/DR/ReportScreen/sections/SetpAdress.js
  app/views/DR/UserInfoScreen/index.js
Labels: ready for review

#83 User-friendly goBack icon in Form
  app/components/DR/Header/index.js
  app/views/DR/ReportScreen/index.js
  app/views/DR/UserInfoScreen/index.js
Labels: ready for review

#85 Added MSP Logo to the end of the form responses
  app/views/DR/ReportScreen/Results.js
Labels: ready for review

#61 Added baseUrls constants to group all URLs and also __DEV__ to pick f…
  .env
  .env.release
  .gitattributes
  .github/workflows/beta-ios.yml
  .github/workflows/build.yml
  .github/workflows/create-release.yml
  app/constants/DR/baseUrls.js
  app/helpers/Intersect.js
  app/services/HCAService.js
  app/views/DR/ReportScreen/ReportScreenQuestions.js
  app/views/DR/UserInfoScreen/index.js
  app/views/LocationTracking.js
  ios/COVIDSafePaths.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Labels: ready for review

#84 Sponsors Screen
  app/Entry.js
  app/assets/images/sponsors/1.png
  app/assets/images/sponsors/10.png
  app/assets/images/sponsors/11.png
  app/assets/images/sponsors/2.png
  app/assets/images/sponsors/3.png
  app/assets/images/sponsors/4.png
  app/assets/images/sponsors/5.png
  app/assets/images/sponsors/6.png
  app/assets/images/sponsors/7.png
  app/assets/images/sponsors/8.png
  app/assets/images/sponsors/9.png
  app/locales/en.json
  app/locales/es.json
  app/views/DR/HomeScreen/index.js
  app/views/DR/Sponsors/List.js
  app/views/DR/Sponsors/index.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
Labels: ready for review

#81 changin datePicker design on android
  app/components/DR/CalendarButton/index.js
  app/locales/en.json
  app/locales/es.json
Labels: ready for review

#87 Feat: legal warning spanish version
  app/assets/SPANISH_LICENSE.json
  app/views/Licenses.js
Labels: ready for review

#86 refactoring phone regex
  .env.release
  app/components/DR/PhoneInput/index.js
Labels: ready for review

#88 Fixing map bug order and misc
  app/components/DR/ButtonUpDrawer.js
Labels: ready for review

#75 Added language translations of the answers form
  app/Entry.js
  app/components/DR/ResultsContent.js
  app/locales/ar.json
  app/locales/da.json
  app/locales/en.json
  app/locales/es.json
  app/locales/fil.json
  app/locales/fr.json
  app/locales/ht.json
  app/locales/id.json
  app/locales/it.json
  app/locales/ja.json
  app/locales/ml.json
  app/locales/nl.json
  app/locales/pl.json
  app/locales/pt_BR.json
  app/locales/ro.json
  app/locales/ru.json
  app/locales/sk.json
  app/locales/vi.json
  app/locales/zh_Hant.json
  app/views/DR/ReportScreen/Results.js
Labels: ready for review

#89 Feature/answers resources
  .env
  app/locales/ar.json
  app/locales/da.json
  app/locales/en.json
  app/locales/es.json
  app/locales/fr.json
  app/locales/id.json
  app/locales/it.json
  app/locales/ja.json
  app/locales/ml.json
  app/locales/nl.json
  app/locales/pl.json
  app/locales/pt_BR.json
  app/locales/ro.json
  app/locales/ru.json
  app/locales/sk.json
  app/locales/vi.json
  app/locales/zh_Hant.json
  app/views/DR/ReportScreen/Results.js
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: ready for review

#92 Original splash
  android/app/src/main/res/drawable/splash.png
  ios/COVIDSafePaths/Images.xcassets/bgImage.imageset/splash-1.png
  ios/COVIDSafePaths/Images.xcassets/bgImage.imageset/splash-2.png
  ios/COVIDSafePaths/Images.xcassets/bgImage.imageset/splash.png
Labels: ready for review

#93 FAQ view
  app/Entry.js
  app/locales/en.json
  app/locales/es.json
  app/locales/faqs/en.json
  app/locales/faqs/es.json
  app/views/DR/FAQ/index.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
Labels: Ready for merge

#94 Add spanish to privacy policy
  app/views/Licenses.js
Labels: ready for review

#95 Feat: pagination bulletin screen
  app/views/DR/News/Bulletins.js
Labels: ready for review

#90 Uppercase news' button label
  app/constants/DR/buttonStyles.js
  app/locales/es.json
  app/views/__tests__/__snapshots__/Import.spec.js.snap
Labels: Ready for merge

#98 Fix positive access and labels
  app/locales/en.json
  app/locales/es.json
  app/views/DR/EpidemiologicalResponseScreen/epidemiologicalStatus.js
  app/views/DR/UserInfoScreen/index.js
Labels: ready for review

#99 Fixing map and hidding Provider Screen in Settings
  app/locales/en.json
  app/locales/es.json
  app/views/DR/Maps/Map.js
  app/views/DR/Maps/MapDialog.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
Labels: ready for review

#80 Positive card
  app/Entry.js
  app/components/DR/ActionCards/ActionCards.js
  app/locales/en.json
  app/locales/es.json
  app/views/DR/HomeScreen/index.js
Labels: ready for review

#103 Remove touchableopacity for disable touch cards
  app/views/DR/HomeScreen/index.js
Labels: ready for review

#102 Share location with alert
  app/locales/en.json
  app/locales/es.json
  app/services/LocationService.js
  app/views/DR/UserInfoScreen/index.js
  app/views/Settings.js
Labels: ready for review

#104 adjusting focus to news section
  app/views/DR/News/Details.js
Labels: ready for review

#112 Positive nicknames and introduction screen
  app/Entry.js
  app/assets/images/covidSick.jpg
  app/components/DR/Header/style.js
  app/constants/colors.js
  app/constants/themes.js
  app/helpers/General.js
  app/locales/en.json
  app/locales/es.json
  app/views/DR/EpidemiologicalResponseScreen/epidemiologicalStatus.js
  app/views/DR/EpidemiologicalResponseScreen/index.js
  app/views/DR/EpidemiologicalResponseScreen/useFor.js
  app/views/DR/ReportScreen/ReportType.js
  app/views/DR/ReportScreen/index.js
  app/views/DR/UserInfoScreen/index.js
  app/views/DR/UserInfoScreen/positiveOnboarding.js
  app/views/Settings.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
Labels: ready for review

#113 Fix: Changed resource name
  app/locales/en.json
  app/locales/es.json
Labels: ready for review

#111 Feat: Using the public doc FAQs to display the data
  app/views/DR/FAQ/index.js
Labels: approved
