Repository intellisysdcorp/covid-safe-paths, pull requests merged in 2020-08, with the labels that each got.

#144 Feat: notify covid positive user
  app/locales/en.json
  app/locales/es.json
  app/services/LocationService.js
  app/views/DR/HomeScreen/index.js
  app/views/DR/UserInfoScreen/index.js
  app/views/DR/UserInfoScreen/positiveOnboarding.js
Labels: approved

#149 new version code for the app in the stores
  android/app/build.gradle
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
Labels: approved

#148 Fix: android sends coordinates
  android/app/build.gradle
  android/app/src/main/java/com/optic/covdr/MainApplication.java
  android/settings.gradle
  app/services/LocationService.js
  ios/Podfile
  jest/setupFile.js
  package.json
  yarn.lock
Labels: ready for review

#150 Feat: notified new subscription ones
  app/services/HCAService.js
  jest/setupFile.js
Labels: approved

#151 Feat: Add webview in cards of dashboard
  app/views/DR/HomeScreen/DashboardCards.js
  app/views/DR/HomeScreen/index.js
  app/views/DR/HomeScreen/style.js
Labels: Ready for merge, approved

#152 Feat: getting advice data from service
  app/constants/DR/RecommendationData.js
  app/views/DR/News/Advices.js
  app/views/DR/News/Bulletins.js
Labels: approved

#154 Changing Terms content and adding styles
  app/locales/eula/en.html
  app/locales/eula/es.html
Labels: approved, ready for review

#157 Changing settings, deleting some options
  app/NavEntry.js
  app/views/Settings.js
  app/views/Settings/SettingsItem.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  jest/config.js
  package.json
  yarn.lock
Labels: ready for review

#158 Updating react-native-pdf
  package.json
  yarn.lock
Labels: ready for review

#156 Fastlane implementation Android
  .gitignore
  android/Gemfile.lock
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  android/fastlane/README.md
  android/fastlane/metadata/android/en-US/changelogs/27.txt
  android/fastlane/metadata/android/en-US/full_description.txt
  android/fastlane/metadata/android/en-US/images/featureGraphic.png
  android/fastlane/metadata/android/en-US/images/icon.
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.
  android/fastlane/metadata/android/en-US/short_description.txt
  android/fastlane/metadata/android/en-US/title.txt
  android/fastlane/metadata/android/en-US/video.txt
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/fastlane/Appfile
  ios/fastlane/Fastfile
  package.json
Labels: approved

#160 Release/1.2.7
  android/app/build.gradle
  app/views/DR/HomeScreen/index.js
  app/views/__tests__/__snapshots__/Import.spec.js.snap
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest/config.js
  package.json
  yarn.lock
Labels: approved

#161 Fix: Changing the way to open JPG advice
  app/views/DR/News/Advices.js
Labels: approved

#163 Fix: Refactoring data list
  .gitignore
  app/components/DR/ActionCards/List.js
  app/components/DR/List.js
  app/views/DR/News/Advices.js
  app/views/DR/News/Bulletins.js
  app/views/DR/News/News.js
Labels: approved

#165 Refactor entry
  android/fastlane/metadata/android/en-US/images/icon.png
  android/fastlane/metadata/android/en-US/images/phoneScreenshots/6_en-US.png
  app/Entry.js
  app/EntryOptions.js
Labels: approved

#164 Hot release/1.2.8
  android/app/build.gradle
Labels: approved

#166 Refactor Home-screen
  app/components/DR/ActionCards/ActionCards.js
  app/components/DR/CasesStatistics.js
  app/components/DR/DashboardCards.js
  app/views/DR/HomeScreen/index.js
  app/views/DR/HomeScreen/style.js
Labels: approved

#167 deleting an unused function and refactor positiveOnboarding dialog
  android/app/build.gradle
  android/app/src/main/java/com/optic/covdr/MainApplication.java
  android/settings.gradle
  app/helpers/General.js
  app/views/DR/ReportScreen/ReportType.js
  app/views/DR/UserInfoScreen/positiveOnboarding.js
  app/views/DR/UserInfoScreen/shareLocationDialog.js
  ios/Podfile
  package.json
Labels: approved

#168 Deleting flotant aurora chat
  app/views/DR/News/Advices.js
  app/views/DR/News/Details.js
Labels: approved

#169 Bump version numbers for release
  android/app/build.gradle
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/Podfile.lock
Labels: approved
